### ISSUE TITLE
Chests show missing texture

### ISSUE THREAD

**Issue by AdamRaichu** [jacobsjo/minecraft-jigsaw-preview#91]
Chests show a missing texture texture instead of looking like a chest. I assume this is because they are [block entities](https://minecraft.fandom.com/wiki/Block_entity#List_of_block_entities).

Great work man, this is looking to be super helpful. Now I don't have to create a new world every time I make a change.

**Comment by jacobsjo** [comment]
You are correct: Since chests are title entities they are not rendered using the normal block models. Since this would normally result in the chest not rendering at all, there is [special code in deepslate](https://github.com/misode/deepslate/blob/52c44ba60df838c640c47e9cf1f471d8532ae08f/src/render/SpecialRenderer.ts#L34) that handles chests separately and explicitly sets the missing texture. Handling the chest texture as well would be more work as the chest texture comes from an entity texture. I don't think that is worth the effort.

**Comment by AdamRaichu** [comment]
Ok, good to know.

**Comment by AdamRaichu** [comment]
Do you happen to know if this is also the case with other tile entities like conduits?

**Comment by jacobsjo** [comment]
Most blocks with block entities still render using normal block model. Entity rendering is only used for: banners, beds, bell, chest, trapped chest, ender chest, conduit, decorated pot, signs, and hanging signs. Of those only the chest, trapped chest and ender chest have the special rendering in deepslate to at least render a cube without texture, the other blocks aren't rendered at all. Since entity models aren't controlled by resource packs - and thus there is no data to reuse by deepslate - there isn't much that can be done about that unfortunately (except re-implementing each model, but that would be rather time consuming).
